# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170828_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrichjson',
            field=models.CharField(default='None', max_length=8000),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 4, 6, 28, 670936)),
        ),
    ]
