# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 02:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170828_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 4, 11, 45, 78905)),
        ),
    ]
