# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 01:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170828_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 3, 18, 20, 630099)),
        ),
        migrations.AlterField(
            model_name='user',
            name='enrich_json',
            field=models.CharField(max_length=8000),
        ),
    ]
